spring.application.name=Lonjevus
spring.servlet.multipart.max-file-size=10MB
spring.web.resources.static-locations=file:C:/Users/User/Desktop/Proyecto Lenguajes/proyecto-lonjevus-back/LonjevusBack/uploads/photos/
spring.mvc.static-path-pattern=/photos/**
